# Generated by Django 5.1 on 2024-08-13 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("user_email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restaurant_name", models.CharField(max_length=255)),
                ("restaurant_owner", models.CharField(max_length=255, null=True)),
                ("owner_number", models.IntegerField(null=True, unique=True)),
                (
                    "owner_email",
                    models.EmailField(max_length=254, null=True, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Review", models.TextField()),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.customer",
                    ),
                ),
                (
                    "restaurant_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.restaurant",
                    ),
                ),
            ],
        ),
    ]
