# Generated by Django 5.1.3 on 2024-11-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="m_user",
            old_name="user_name",
            new_name="full_name",
        ),
    ]
