# Generated by Django 5.1 on 2024-08-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="user_password",
            field=models.CharField(default="0", max_length=10),
        ),
    ]
