# Generated by Django 5.1 on 2024-10-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_customer_user_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leaderborad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restaurant_name", models.CharField(max_length=255)),
                ("score", models.CharField(max_length=255)),
            ],
        ),
    ]
