# Generated by Django 5.1 on 2024-10-09 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_leaderborad"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Leaderborad",
            new_name="Leaderborad_backup",
        ),
    ]
